# Generated by Django 2.0.2 on 2018-02-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'about'},
        ),
        migrations.AlterModelOptions(
            name='compendia',
            options={'verbose_name_plural': 'compendia'},
        ),
        migrations.AlterModelOptions(
            name='supplementary',
            options={'verbose_name_plural': 'supplementaries'},
        ),
        migrations.AddField(
            model_name='about',
            name='comment',
            field=models.CharField(default='About page text update', max_length=2000),
        ),
    ]
